highlighter: pygments
github: [Repository metadata]
paginate: 5
paginate_path: "/blog/page:num"

author: arlen
title: Arlen.Ren's Blog
keywords: Arlen 任亚荣 Java
description: sss
navigations: [{ls: ddd, dd: 222}, {ls: sss, dd: 333}]