encoding: utf-8
#3.0之后默认用rouge
#highlighter: pygments
github: [Repository metadata]
base_url: http://arlen43.github.io
paginate: 5
paginate_path: "/blog/page:num"

author: Arlen.Ren
title: Arlen.Ren's Blog
keywords: Arlen 任亚荣 Java Spring
description: 任亚荣的技术博客
navigations: [{ls: ddd, dd: 222}, {ls: sss, dd: 333}]